# Netlify配置文件
[build]
  command = "node build.js"  # 使用我们的构建脚本
  publish = "dist"           # 所有项目的构建输出目录

# 针对单页应用的重定向规则
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 在构建时处理的环境变量
[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--version"  # 避免npm install
  
# 使用pnpm作为包管理器  
[build.lifecycle]
  onInstall = "corepack enable && corepack prepare pnpm@latest --activate && pnpm install --no-frozen-lockfile" 