[build]
  command = "pnpm build:netlify"
  publish = "mainApp/dist"
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- mainApp/ build-netlify.js package.json pnpm-workspace.yaml pnpm-lock.yaml"

# 安装 pnpm
[[plugins]]
  package = "@nrwl/workspace/plugins/netlify"

# 针对预览环境的配置
[context.deploy-preview]
  command = "pnpm build:netlify"
  
# 针对分支部署的配置
[context.branch-deploy]
  command = "pnpm build:netlify"

# 重定向设置，确保SPA路由正常工作
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 