[build]
  base = "/"
  command = "npm run build:netlify"
  publish = "apps/mainApp/dist"

# 为子项目配置重定向规则
[[redirects]]
  from = "/fish-pond/*"
  to = "/fish_pond/:splat"
  status = 200

[[redirects]]
  from = "/choo-choo-train/*"
  to = "/choo_choo_train/:splat"
  status = 200

[[redirects]]
  from = "/spine-boy-adventure/*"
  to = "/spine_boy_adventure/:splat"
  status = 200

# SPA 回退规则
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 