[build]
  # 删除错误的base配置，改为在Netlify UI中设置package directory
  command = "pnpm build"
  publish = "dist"
  # 只在该应用目录下的文件变更时触发构建
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- ."

# 重定向设置，确保SPA路由正常工作
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 