[build]
  command = "pnpm build"
  publish = "dist"
  # 只在该应用目录下的文件变更时触发构建
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- . ../shared/ ../../package.json ../../pnpm-workspace.yaml ../../pnpm-lock.yaml"

# 重定向设置，确保SPA路由正常工作
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 